default_language_version:
  python: python3

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff-format
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [ --pytest-test-first ]
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [ --fix=auto ]
      - id: fix-byte-order-marker
        exclude: .gitignore
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.8.0
    hooks:
      - id: zizmor
  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.3
    hooks:
      - id: poetry-check
  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: 1.9.0
    hooks:
      - id: poetry-export
        name: Export Poetry requirements.txt
        args:
          - --format=requirements.txt
          - --output=requirements.txt
          - --without-hashes
          - --all-groups
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
